    [uwsgi]
    ; This is the entry point to our application.
    ; It means: in the 'init.py' file, find the variable named 'app'.
    module = init:app

    ; Allow the master process to manage worker processes
    master = true
    ; Number of worker processes to spawn (a good starting point is 2x CPU cores)
    processes = 4

    ; The socket to bind to. 0.0.0.0 means it's accessible from outside the container.
    http = 0.0.0.0:5000

    ; Automatically clean up the socket file on exit
    vacuum = true
    ; A setting that helps Docker stop the container gracefully
    die-on-term = true
    enable-threads = true
